name: Chatops
on: [issue_comment]

jobs:
  trigger-chatops:
    if: (github.event.issue.pull_request != null) &&  contains(github.event.comment.body, '/preview')
    runs-on: ubuntu-latest
    steps:
          
      - name: see payload
        run: |
          echo "FULL PAYLOAD:\n${PAYLOAD}\n"
          echo "PR_PAYLOAD PAYLOAD:\n${PR_PAYLOAD}"
        env:
          PAYLOAD: ${{ toJSON(github.event) }}
          PR_PAYLOAD: ${{ github.event.pull_request }}
          
