name: Chatops
on: [issue_comment]

jobs:
  trigger-chatops:
    if: (github.event.issue.pull_request != null) &&  contains(github.event.comment.body, '/preview')
    runs-on: ubuntu-latest
    steps:
          
      - name: see payload
        run: |
          echo "${PAYLOAD}"
        env:
          PAYLOAD: ${{ toJSON(github.event.issue.number) }}
          

      - name: comment on PR with Binder link
        uses: actions/github-script@v1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(context.payload.issue.number)           
            github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.issue.number
            }).then( (val) => console.log(val.head.ref))
        env:
          PR_NUM: ${{ github.event.pull_request.data.head.ref }}
