name: condition
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Build app
        id: build
        run: |
          echo ::set-output name=exit_code::$?
          exit 1;
          
      - name: Create artifact of test coverage
        run: "echo Wooo!"
        if: steps.build.outputs.exit_code == 1
