name: condition
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Step1
        id: build
        run: |
          echo "::set-output name=exit_code::1"
          exit 1;
          
      - name: Step2
        run: echo "Wooo!"
        if: 1 == 1
