name: Container Options
on: push
  
jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: fastdotai/fastai2
      options: "--user=root"
    env:
      auto_fix: false  
    steps:
    - name: see user
      run: whoami
