name: Test
on: push

jobs:    
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        var: ['true', 'false', '']
        include:
          - var: 'true'
            var2: 'only when the other is true'
        
    steps:
      - name: emit values
        run: |
          echo "The value:$VALUE"
          echo "The second value: $VALUE2"
        env:
          VALUE: ${{ matrix.var }}
          VALUE2: ${{ matrix.var2 }}
