name: Pull-Request-Target
on: 
  workflow_dispatch: #allows repo admins to trigger this workflow from the Actions tab
  pull_request_target:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: see payload
      run: |
        echo "${PAYLOAD}"
      env:
        PAYLOAD: ${{ toJSON(github.event.head.ref) }}

    - name: checkout contents of PR
      uses: actions/checkout@v2
      with:
        ref: ${{github.event.head.ref}}
    
    - name: see files
      run: ls
 
