name: pull request payload
on:
  pull_request
  
jobs:
  binder:
    runs-on: ubuntu-latest
    steps:
       
    - name: see payload
      run: |
        echo "${PAYLOAD}"
      env:
        PAYLOAD: ${{ toJSON(github.event) }}

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
      
