name: see payload
on: [push]

jobs:
  binder:
    runs-on: ubuntu-latest
    steps:
       
    - name: see payload
      run: |
        echo "${PAYLOAD}"
      env:
        PAYLOAD: ${{ toJSON(github.event) }}
