name: pull request payload
on:
  pull_request
  
jobs:
  binder:
    runs-on: ubuntu-latest
    steps:
   
    - name: see payload
      run: |
        echo "${PAYLOAD}"
      env:
        PAYLOAD: ${{ toJSON(github.event) }}

    - uses: actions/checkout@main
    - name: Commit back to GitHub
      run: |
        touch something.txt
        git add -A
        git commit --allow-empty -m'update docs'
        git push
      
