name: see-secrets
on:
  push:

jobs:     
  build-site:
    runs-on: ubuntu-latest
    steps:

    - name: see payload
      run: echo "$PAYLOAD"
      env:
        PAYLOAD: ${{ toJSON(github.event) }}

    - name: Copy Repository Contents
      uses: actions/checkout@master
      with:
        persist-credentials: false

    - name: execute local action
      run: |
        echo "See Token:"
        echo $GITHUB_TOKEN

 
